DROP database IF EXISTS `test-server`;

CREATE database IF NOT EXISTS `test-server`;
use `test-server`;

CREATE TABLE `EMPLOYEE` (
  `EMPID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPNAME` varchar(45) DEFAULT NULL,
  `DOB` varchar(45) DEFAULT NULL,
  `SALARY` int(11) DEFAULT NULL,
  `AGE` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


INSERT INTO `EMPLOYEE` (`EMPID`,`EMPNAME`,`DOB`,`SALARY`,`AGE`) VALUES (1,'Tim','07/22/2000',60000, 21);